version: "3.3"
services:
  app-spa-spa-dev:
    build: 
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../:/app
    networks:
      - overlay
volumes:
  app:
networks:
  overlay: